
title: Across the Universe.
description: >- # this means to ignore newlines until "baseurl:"
  This is my playground. And This is some extra description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://naduhy2.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Seoul
github_username:  naduhy2
google_analytics: UA-129096911-1

# About
author:
  name: DeokHyeon Nam
  email: darren.nam@gmail.com
  github: naduhy2

# Build settings
permalink: /:year/:month/:title:output_ext
markdown: kramdown
highlighter: rouge
comments: true
plugins:
  - jekyll-feed
collections:
  category:
    output: true
    permalink: /category/:path/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ''
      type: category
    values:
      layout: category
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
