
title: Across the Universe.
description: This is my playground.
baseurl: "/blog"
url: "http://naduhy2.github.io"

timezone: Asia/Seoul
google_analytics: UA-129096911-1

# About
author:
  name: DeokHyeon Nam
  email: darren.nam@gmail.com
  github: naduhy2

sass:
  sass_dir: assets/css/
  style: :compressed

# Build settings
permalink: /:year/:month/:title:output_ext
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

comments: true
plugins:
  - jekyll-feed
collections:
  category:
    output: true
    permalink: /category/:path/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ''
      type: category
    values:
      layout: category
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
